### ISSUE TITLE
Fix models is not defined in db ops

### ISSUE THREAD

**Issue by fedorgrab** [cellarium-ai/cellarium-cloud#64]
```
Traceback (most recent call last):
  File "/casp/cell-annotation-service-pilot/src/casp/services/api/server.py", line 14, in <module>
    from casp.services.db import init_db, models, ops
  File "/casp/cell-annotation-service-pilot/src/casp/services/db/ops.py", line 9, in <module>
    def increment_user_cells_processed(user: models.User, number_of_cells: int) -> None:
NameError: name 'models' is not defined
```

**Comment by fedorgrab** [comment]
The issue was with type annotation in function definition:
`def increment_user_cells_processed(user: models.User, number_of_cells: int) -> None:`
Either include:
`from __future__ import annotations`
or stringify type annotation
